// Generato/aggiornato in Fase 6 a partire da data/jobs/jobs.json.
// Caricato via <script> (non fetch) perché index.html è pensato per essere
// aperto direttamente in locale (file://), dove fetch() di un JSON locale
// verrebbe bloccato dal browser.
const JOBS = [
  {
    "slug": "oliver-wyman-data-analytics-senior-analyst-milan",
    "title": "Data & Analytics — Senior Analyst",
    "company": "Oliver Wyman",
    "location": "Milano",
    "remote": null,
    "url": "https://it.linkedin.com/jobs/view/oliver-wyman-data-analytics-senior-analyst-milan-at-oliver-wyman-3237198599",
    "source": "LinkedIn (via ricerca web)",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Team Data & Analytics Milano (circa 25 persone)",
      "Profilo quantitativo per attività di analytics"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Consulenza di alto livello (management consulting strategico) — buon fit con il criterio 'consulenza solo se alto livello'. Trovato solo tramite snippet di ricerca web: link non verificato direttamente (WebFetch bloccato in questo ambiente). Apri il link e incolla qui il testo dell'annuncio per completare match tecnico (Fase 3) e verifica economica/mission (Fase 4).",
    "status": "scartato",
    "discard_reason": "Scartato dall'utente dalla dashboard (click su \"Scarta\").",
    "cv_path": null
  },
  {
    "slug": "intesa-sanpaolo-data-analyst-milano",
    "title": "Data Analyst — Group Technology, Data Domain",
    "company": "Intesa Sanpaolo",
    "location": "Milano",
    "remote": null,
    "url": "https://it.linkedin.com/jobs/view/data-analyst-at-intesa-sanpaolo-3774737280",
    "source": "LinkedIn (via ricerca web)",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Business requirements analysis per soluzioni IT",
      "Gestione relazioni con business owner",
      "Documenti di analisi funzionale, verifica processi IT"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande gruppo bancario italiano — buon fit su dimensione/brand. Il livello (Analyst generico, non esplicitamente Senior) va verificato: potrebbe essere sotto la seniority target. Link non verificato direttamente (WebFetch bloccato). Apri il link e incolla il testo dell'annuncio per completare Fase 3/4.",
    "status": "scartato",
    "discard_reason": "Scartato dall'utente dalla dashboard (click su \"Scarta\").",
    "cv_path": null
  },
  {
    "slug": "sky-italia-data-governance-manager",
    "title": "Manager - Data Governance",
    "company": "Sky Italia",
    "location": "Milano (Monte Penice) / Cagliari / Roma",
    "remote": null,
    "url": "https://careers.sky.com/it/en/jobs/R0051694",
    "source": "Ricerca Tavily (career page ufficiale Sky, rif. R0051694) — trovato link diretto, verificato ATTIVO (reference reale, pulsante Apply funzionante, ripubblicato di recente su mirror builtin.com) il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Ruolo di Manager - Data Governance, Dipartimento Data Infrastructure",
      "Posizione aperta anche a Cagliari e Roma oltre a Milano"
    ],
    "technical_match_score": "Fit incerto: ruolo di Data Governance (framework, qualità dati, compliance) — profile.yaml non documenta esperienza diretta di data governance (più orientato a BI/analytics/forecasting). Testo integrale dell'annuncio non disponibile: sia careers.sky.com sia il mirror builtin.com mostrano un template con sezioni vuote ('What you'll do', 'What you'll bring', 'Where you'll work' tutte con placeholder 'XXX'), probabile bug del sito Sky. Valutazione basata solo su titolo/reparto/sede.",
    "economic_fit": "unknown",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (link diretto trovato con reference R0051694, non più solo pagina aziendale generica). RAL non dichiarata. Ottimo fit di settore/mission (Sky/Comcast, media, coerente con Mediaset/Publitalia), ma ambito tecnico (data governance) diverso dal core BI/analytics del profilo e RAL sconosciuta: da valutare con l'utente prima di generare il CV, non generato in questa sessione.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "sky-italia-business-customer-insight-analyst",
    "title": "Business & Customer Insight Analyst",
    "company": "Sky Italia",
    "location": "Milano",
    "remote": null,
    "url": "https://it.linkedin.com/jobs/sky-italia-offerte-di-lavoro",
    "source": "LinkedIn (via ricerca web, pagina aziendale — non link diretto all'annuncio)",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Trasformare i dati in decisioni di business"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Molto coerente con l'esperienza Marketing Data Analyst su audience/media analytics (Mediaset/Publitalia). Livello seniority del ruolo da verificare (non chiaro se Senior). Link solo alla pagina offerte aziendale, non al posting specifico. WebFetch bloccato in questo ambiente.",
    "status": "scartato",
    "discard_reason": "Scartato dall'utente dalla dashboard (click su \"Scarta\").",
    "cv_path": null
  },
  {
    "slug": "generali-workforce-planning-people-analytics-manager",
    "title": "Group Workforce Planning & People Analytics Manager",
    "company": "Generali",
    "location": "Milano",
    "remote": null,
    "url": "https://it.linkedin.com/company/generali/jobs",
    "source": "LinkedIn (via ricerca web, pagina aziendale — non link diretto all'annuncio)",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Analytics a livello di gruppo (people/workforce planning)"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande gruppo assicurativo italiano/multinazionale — ottimo fit su dimensione/brand, ruolo di livello Manager coerente con seniority target. Ambito (people/workforce analytics) leggermente diverso da marketing/business analytics del CV: verificare pertinenza.",
    "status": "scartato",
    "discard_reason": "Verificato con Tavily: pagina dell'annuncio specifico (generali.referrals.selectminds.com) conferma esplicitamente 'Unfortunately this position has been closed' — posizione chiusa.",
    "cv_path": null
  },
  {
    "slug": "campari-group-commercial-insights-analytics-associate-manager",
    "title": "Commercial Insights & Analytics Associate Manager (East/Franchise Regions)",
    "company": "Campari Group",
    "location": "Milano (HQ) — ruolo riferito a regioni East/Franchise, da verificare sede effettiva",
    "remote": null,
    "url": "https://salaryguide.com/jobs/commercial-insights-analytics-associate-manager-ea-campari-group-d979d8",
    "source": "Ricerca web (aggregatore, non fonte ufficiale)",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Governance e analytics a supporto della strategia commerciale"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale con HQ a Milano — buon fit su dimensione/brand a livello di gruppo.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): sede effettiva New York, USA (non Milano) e \"This job is no longer accepting applications\" (posted 8 mesi fa) — doppio motivo di scarto.",
    "cv_path": null
  },
  {
    "slug": "essilorluxottica-senior-ecommerce-business-analyst-milano",
    "title": "Senior e-Commerce Business Analyst",
    "company": "EssilorLuxottica",
    "location": "Milano",
    "remote": null,
    "url": "https://careers.essilorluxottica.com/job/Milano-E-commerce-Business-Analyst/991279501/",
    "source": "Ricerca web (career page ufficiale EssilorLuxottica)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale italiana (eyewear), livello Senior esplicito nel titolo — buon fit su seniority/dimensione. Ambito e-commerce piuttosto che marketing/business analytics puro.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): \"Sorry, this position has been filled.\" — posizione già coperta.",
    "cv_path": null
  },
  {
    "slug": "essilorluxottica-data-intelligence-analyst-milano",
    "title": "Data Intelligence Analyst",
    "company": "EssilorLuxottica (Luxottica)",
    "location": "Milano",
    "remote": null,
    "url": "https://it.jooble.org/rjdp/5573388073315939616",
    "source": "Jooble (aggregatore, non fonte ufficiale)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale italiana — buon fit su dimensione/brand. Livello seniority non esplicito nel titolo. Fonte aggregatore terzo (Jooble), non la pagina ufficiale.",
    "status": "scartato",
    "discard_reason": "Link non raggiungibile in verifica (Tavily: \"Failed to fetch url\") — fonte aggregatore inaffidabile, scartato per prudenza invece di lasciarlo non verificato.",
    "cv_path": null
  },
  {
    "slug": "ey-parthenon-senior-manager-strategy-financial-services-milano",
    "title": "Senior Manager - Strategy - EY-Parthenon - Financial Services",
    "company": "EY-Parthenon (EY)",
    "location": "Milano",
    "remote": null,
    "url": "https://careers.ey.com/ey/job/Milano-Senior-Manager-Strategy-EY-Parthenon-Financial-Services-20123/1099031101/",
    "source": "Ricerca web (career page ufficiale EY)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Consulenza strategica di alto livello (EY-Parthenon è il ramo strategy di EY) — ottimo fit col criterio 'consulenza solo se alto livello', ruolo Senior Manager coerente con seniority target.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): \"The Job is no longer available.\"",
    "cv_path": null
  },
  {
    "slug": "ey-parthenon-senior-corporate-strategy-milano",
    "title": "Senior - EY-Parthenon - Corporate Strategy",
    "company": "EY-Parthenon (EY)",
    "location": "Milano",
    "remote": null,
    "url": "https://careers.ey.com/ey/job/Milano-Senior-EY-Parthenon-Corporate-Strategy-20123/1218621801/",
    "source": "Ricerca web (career page ufficiale EY)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Consulenza strategica di alto livello — ottimo fit col criterio 'consulenza solo se alto livello'. Livello 'Senior' (non Manager) rispetto a 5+ anni di esperienza.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): \"The Job is no longer available.\"",
    "cv_path": null
  },
  {
    "slug": "deloitte-insights-and-analytics-senior-manager",
    "title": "Insights and Analytics Senior Manager",
    "company": "Deloitte",
    "location": "Italia — sede specifica (Milano/Roma) da verificare",
    "remote": null,
    "url": "https://apply.deloitte.com/en_US/careers/JobDetail/Insights-and-Analytics-Senior-Manager/321335",
    "source": "Ricerca web (career page ufficiale Deloitte)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Consulenza di alto livello (Deloitte / area Strategy, Analytics & M&A) — ottimo fit su seniority (Senior Manager) e sul criterio consulenza alto livello.",
    "status": "scartato",
    "discard_reason": "Link non raggiungibile in verifica (Tavily: \"404 page not found\") — annuncio rimosso.",
    "cv_path": null
  },
  {
    "slug": "prada-group-data-analytics-delivery-lead-milano",
    "title": "Data Analytics Delivery Lead",
    "company": "Prada Group",
    "location": "Milano",
    "remote": null,
    "url": "https://www.businessoffashion.com/careers/job/306331/data-analytics-delivery-lead/",
    "source": "Business of Fashion (career page ufficiale Prada Group)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [
      "Coordinamento delivery di tre team interni (Data Visualization, Data Science, Data Lake)",
      "Gestione interfacce con altri team IT"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale italiana del lusso, HQ Milano — ottimo fit su dimensione/brand. Ruolo di coordinamento/leadership coerente con seniority target.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): \"This job has expired\" (closing date 7 Apr 2026).",
    "cv_path": null
  },
  {
    "slug": "prada-group-app-analytics-lead-milano",
    "title": "App Analytics Lead",
    "company": "Prada Group",
    "location": "Milano",
    "remote": null,
    "url": "https://www.businessoffashion.com/careers/job/309810/app-analytics-lead/",
    "source": "Business of Fashion (career page ufficiale Prada Group)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [
      "Analytics performance app mobile su ecosistema B2C/B2B",
      "Insight generation per engagement, retention e impatto business"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale italiana del lusso, HQ Milano — ottimo fit su dimensione/brand e su analytics/business insight, molto vicino all'esperienza in audience/consumer analytics del CV.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): \"This job has expired\" (closing date 27 Aug 2026, scaduto ieri/oggi).",
    "cv_path": null
  },
  {
    "slug": "kering-people-insights-analytics-partner-milano",
    "title": "People Insights & Analytics Partner",
    "company": "Kering",
    "location": "Milano",
    "remote": null,
    "url": "https://aijobs.net/job/kering-people-insights-analytics-partner-milano-milano-italy-248744/",
    "source": "aijobs.net (aggregatore, non fonte ufficiale)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale del lusso (Gucci, Saint Laurent, ecc.) — ottimo fit su dimensione/brand. Ambito 'People' (HR analytics) diverso da marketing/business analytics del CV.",
    "status": "scartato",
    "discard_reason": "Verificato con lettura pagina reale (Tavily): \"Expired 27d ago\".",
    "cv_path": null
  },
  {
    "slug": "ferrero-business-intelligence-analytics-function",
    "title": "Business Intelligence & Analytics (BI&A) — funzione, ruolo specifico da individuare",
    "company": "Ferrero",
    "location": "Italia — sede specifica da verificare (HQ Alba/uffici Milano)",
    "remote": null,
    "url": "https://www.ferrerocareers.com/us/en/jobs",
    "source": "Ricerca web (career page ufficiale Ferrero, non link diretto a un singolo annuncio)",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [
      "Supporto a decisioni strategiche cross-categoria tramite BI&A"
    ],
    "technical_match_score": null,
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Grande multinazionale italiana FMCG — buon fit su dimensione/brand.",
    "status": "scartato",
    "discard_reason": "Ricerca reale su ferrerocareers.com (Tavily) non ha trovato nessun annuncio attivo di Business Intelligence & Analytics a livello Manager/Senior in Italia. Il ruolo più affine trovato, 'Business Intelligence & Commercial Planning Manager', è disponibile solo a Seoul (Corea del Sud), non in Italia — nessun posting concreto da valutare per questa sessione.",
    "cv_path": null
  },
  {
    "slug": "ey-parthenon-corporate-strategy-senior-consultant-milano-v2",
    "title": "EY-Parthenon - Corporate Strategy - Senior Consultant",
    "company": "EY-Parthenon (EY)",
    "location": "Milano",
    "remote": null,
    "url": "https://careers.ey.com/ey/job/Milano-EY-Parthenon-Corporate-Strategy-Senior-Consultant-MI-20144/1407997933",
    "source": "Ricerca Tavily (career page ufficiale EY) — verificato ATTIVO leggendo il testo integrale il 29/08/2026",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [
      "Team EY-Parthenon Strategy Italia, sede Milano",
      "Approccio analitico ed entrepreneurial mindset",
      "Uso di strumenti AI/tech (Copilot365, PowerBI) a supporto dell'analisi"
    ],
    "technical_match_score": "Fit moderato: ruolo di consulenza strategica generalista (non execution analytics/BI). L'esperienza analitica e data-driven del profilo è rilevante e trasferibile, ma il day-to-day (project work di strategy consulting) è diverso dal lavoro BI/reporting/forecasting descritto in profile.yaml. Buon fit sul criterio 'consulenza di alto livello'.",
    "economic_fit": "ok",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (letto testo integrale via Tavily il 29/08/2026, nessun segnale di chiusura; ri-confermato ancora attivo il 28/08/2026 in questa sessione). RAL dichiarata: EUR 45.000–55.000 (CCNL Commercio) — sopra la soglia minima di 45k in goals.yaml. Consulenza di alto livello, coerente con gli obiettivi di crescita/sfide in goals.yaml. Livello 'Senior Consultant' (non Manager): possibile leggero sotto-livello rispetto a 5+ anni target — CV generato comunque su richiesta esplicita dell'utente (Fase 4 superata: economic_fit e mission_fit entrambi ok); caveat di seniority segnalato per la decisione finale dell'utente.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/ey-parthenon-corporate-strategy-senior-consultant-milano-v2/cv.md"
  },
  {
    "slug": "sky-italia-manager-data-scientist-milano",
    "title": "Manager Data Scientist",
    "company": "Sky Italia",
    "location": "Milano (Monte Penice, Rogoredo)",
    "remote": "ibrido, fino a 12 giorni/mese remote working",
    "url": "https://careers.sky.com/it/en/jobs/R0056463",
    "source": "Ricerca Tavily (career page ufficiale Sky, rif. R0056463) — verificato ATTIVO leggendo il testo integrale il 29/08/2026",
    "date_found": "2026-08-29",
    "date_posted": null,
    "key_requirements": [
      "Almeno 4 anni di esperienza in data science/advanced analytics",
      "Python (Pandas, NumPy, Scikit-learn), SQL, machine learning, produzione modelli in ambienti di produzione",
      "Ruolo da senior individual contributor con leadership strategica su iniziative cross-funzionali, non people management"
    ],
    "technical_match_score": "Fit misto: ottima coerenza di settore/mission (broadcast/media, molto vicino a Mediaset/Publitalia in profile.yaml — audience, TV, dati media). Fit tecnico parziale: il ruolo è orientato a data science/ML engineering hands-on (produzione modelli, Scikit-learn, Git) mentre il profilo è più orientato a BI/analytics/reporting/forecasting (Power BI, Qlik, PySpark, KPI framework). Skill Python/SQL/ML presenti nel profilo ma non a livello di produzione ML.",
    "economic_fit": "ok",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (letto testo integrale via Tavily il 29/08/2026, nessun segnale di chiusura/filled; ri-confermato ancora attivo il 28/08/2026 in questa sessione). RAL dichiarata: da EUR 51.000 lordi/anno (CCNL Radio-TV) — sopra la soglia minima di 45k e vicino/oltre il target 50k in goals.yaml. Grande gruppo media multinazionale (Sky Group/Comcast) — ottimo fit su dimensione, brand e settore rispetto all'esperienza Mediaset/Publitalia. Il gap tecnico (ML engineering vs BI/analytics) resta reale — CV generato comunque su richiesta esplicita dell'utente (Fase 4 superata: economic_fit e mission_fit entrambi ok), enfatizzando solo competenze ML/Python/audience analytics realmente presenti nel profilo, senza forzare nulla di non presente in profile.yaml.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/sky-italia-manager-data-scientist-milano/cv.md"
  },
  {
    "slug": "avolta-global-principal-data-analyst-milano",
    "title": "Global Principal Data Analyst",
    "company": "Avolta",
    "location": "Milano (alternativa: Madrid)",
    "remote": null,
    "url": "https://careers.avoltaworld.com/job/Global-Principal-Data-Analyst/1387503033",
    "source": "Ricerca Tavily (career page ufficiale Avolta) — verificato ATTIVO leggendo il testo integrale il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "8+ anni di esperienza in Analytics/BI/Data Science/Consulting/Revenue Management",
      "SQL avanzato e Python; ecosistemi analytics moderni (Databricks, Snowflake, Azure, AWS, GCP)",
      "Power BI/Tableau/Looker; ruolo individual contributor senior che riporta al Global Strategy Senior Manager"
    ],
    "technical_match_score": "Fit buono su strumenti e ambito (SQL, Python, Power BI, KPI framework, forecasting, stakeholder management tutti presenti nel profilo), ma il livello di esperienza richiesto (8+ anni) supera l'esperienza reale del profilo (circa 5 anni). Ruolo 'Principal' molto senior come individual contributor globale.",
    "economic_fit": "unknown",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily). Avolta è una grande multinazionale travel retail/F&B (ex Dufry, fusa con Autogrill, 5.500 punti vendita in 75+ paesi) — contesto dinamico e in trasformazione, coerente con 'azienda dinamica, sfide nuove' di goals.yaml. Sede Milano disponibile (alternativa Madrid). Nessuna RAL dichiarata: da chiedere in colloquio. Gap di esperienza (8+ anni richiesti vs ~5 anni reali) resta il principale rischio tecnico — CV generato comunque su richiesta esplicita dell'utente, enfatizzando SQL/Python/Power BI, KPI framework, forecasting e stakeholder management realmente presenti nel profilo, senza aggiungere anni di esperienza o competenze non documentate in profile.yaml. Caveat di seniority ('Principal', 8+ anni) segnalato per la decisione finale dell'utente; RAL da verificare in colloquio.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/avolta-global-principal-data-analyst-milano/cv.md"
  },
  {
    "slug": "metro-italia-customer-analytics-leader-san-donato",
    "title": "Customer Analytics Leader",
    "company": "METRO Italia (METRO/MAKRO)",
    "location": "San Donato Milanese (MI)",
    "remote": "ibrido",
    "url": "https://simplify.jobs/p/e94f1e0c-2158-4302-8715-7b84399b21ee/Customer-Analytics-Leader",
    "source": "Ricerca Tavily (mirror di annuncio ufficiale METRO Italia, testo con dettagli contrattuali espliciti) — verificato il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Laurea magistrale in economia o discipline STEM",
      "3 anni di esperienza in ruoli/funzioni simili",
      "SQL, strumenti BI (MicroStrategy, QlikView, Qlik Sense), analisi transazionale clienti e segmentazione, GDPR"
    ],
    "technical_match_score": "Fit tecnico buono (SQL, BI, analisi comportamentale cliente presenti nel profilo), ma il livello richiesto (3 anni) è sotto la seniority target di 5+ anni — ruolo probabilmente più junior/mid rispetto al profilo.",
    "economic_fit": "below_target",
    "mission_fit": "unknown",
    "fit_notes": "Annuncio con dettagli contrattuali espliciti: RAL dichiarata € 42.000 lordi/anno (CCNL Distribuzione Moderna Organizzata), sotto la soglia minima non negoziabile di € 45.000 in goals.yaml. Scartato per soglia economica prima di valutare mission_fit, come da regola 6 di CLAUDE.md.",
    "status": "scartato",
    "discard_reason": "RAL dichiarata € 42.000 lordi/anno, sotto la soglia minima non negoziabile di € 45.000 in goals.yaml.",
    "cv_path": null
  },
  {
    "slug": "allianz-manager-business-intelligence-analytics-remote-us",
    "title": "Manager, Business Intelligence and Analytics",
    "company": "Allianz Partners",
    "location": "Richmond, Virginia, USA (remote, riservato a residenti autorizzati in stati USA selezionati)",
    "remote": true,
    "url": "https://careers.allianz.com/global/en/job/95134/Manager-Business-Intelligence-and-Analytics",
    "source": "Ricerca Tavily (career page ufficiale Allianz) — verificato leggendo il testo integrale il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "7+ anni in analytics/data strategy, 3+ anni di leadership di team preferiti",
      "Power BI avanzato, SQL, Python",
      "Posizione 100% remote riservata a candidati già residenti in stati USA selezionati (FL, GA, MD, NC, TX, VA, IL, KY, MN, SC, PA, TN)"
    ],
    "technical_match_score": "Fit tecnico buono su strumenti (Power BI, SQL, Python, team leadership analytics), ma il ruolo è irraggiungibile per vincoli di sede/eleggibilità al lavoro.",
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "Non compatibile con i criteri di location/mobilità: posizione remote riservata a candidati già residenti e autorizzati al lavoro in specifici stati USA, non raggiungibile come trasferimento a Milano/Italia né come assignment breve dall'Italia. Scartato per mismatch di sede/eleggibilità prima di valutare economic_fit/mission_fit.",
    "status": "scartato",
    "discard_reason": "Posizione 100% remote riservata a candidati già residenti e autorizzati al lavoro in stati USA selezionati; non compatibile con i criteri di location/mobilità (Milano/Italia/estero come assignment o posizione intera raggiungibile dall'Italia).",
    "cv_path": null
  },
  {
    "slug": "roland-berger-senior-consultant-milano",
    "title": "Senior Consultant",
    "company": "Roland Berger",
    "location": "Milano",
    "remote": null,
    "url": "https://www.rolandberger.com/en/Join/All-Jobs/Senior-Consultant-REF4275X.html",
    "source": "Ricerca Tavily (career page ufficiale Roland Berger) — verificato ATTIVO leggendo il testo integrale il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "Esperienza estesa in management consulting; sviluppo/raffinamento di framework e template strategici",
      "Guida clienti su sfide di business complesse, all'intersezione tra strategia ed esecuzione",
      "Costruzione e mentoring di un team ad alte prestazioni"
    ],
    "technical_match_score": "Fit moderato: ruolo di consulenza strategica generalista (Roland Berger è tra le principali strategy consultancy al mondo) — ottimo fit col criterio 'consulenza solo se alto livello'. L'approccio analitico e la capacità di sintetizzare dati complessi del profilo sono trasferibili, ma il day-to-day (project work di strategy consulting, gestione team) è diverso dal lavoro di BI/reporting/forecasting descritto in profile.yaml.",
    "economic_fit": "ok",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily, pagina con pay transparency esplicita). RAL dichiarata € 75.000–85.000 lordi + bonus fino al 30% — ben sopra la soglia minima 45k e il target 50k in goals.yaml, la migliore offerta economica trovata finora. Consulenza strategica top-tier, cultura 'entrepreneurship, excellence, empathy' coerente con la ricerca di sfide nuove e crescita reale in goals.yaml. Come per gli altri ruoli EY-Parthenon già in pipeline: fit tecnico moderato (competenze trasferibili ma ambito diverso da BI/analytics puro), ma Fase 4 pienamente superata.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/roland-berger-senior-consultant-milano/cv.md"
  },
  {
    "slug": "moncler-stone-island-client-insights-analyst-milano",
    "title": "Client Insights Analyst (Stone Island)",
    "company": "Moncler Group (Stone Island)",
    "location": "Milano",
    "remote": null,
    "url": "https://jobs.monclergroup.com/moncler-careers/jobs/33302?lang=en-gb",
    "source": "Ricerca Tavily (career page ufficiale Moncler Group) — verificato ATTIVO leggendo il testo integrale il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "5-7 anni di esperienza in CRM analytics, customer intelligence, business analytics",
      "Strumenti CRM e BI (Salesforce, Power BI, Tableau, Dynamics); SQL un plus",
      "Segmentazione clienti, dashboard, KPI CRM, stakeholder management"
    ],
    "technical_match_score": "Fit molto buono: analisi comportamento cliente, dashboard KPI, BI tools — in linea con l'esperienza Mediaset/Publitalia e Jakala. Seniority richiesta (5-7 anni) coerente col profilo.",
    "economic_fit": "below_target",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily). Fit tecnico e di seniority molto buono, ma la fascia RAL dichiarata (€ 38.000–48.000 lordi, CCNL Tessile) è in gran parte sotto la soglia minima non negoziabile di 45k: solo la parte alta della fascia la supera, nessuna garanzia di rientrare sopra soglia. Grande gruppo lusso italiano (Moncler/Stone Island) — ottimo fit su dimensione/brand/dinamicità. Non genero CV in questa sessione: da valutare con l'utente se procedere puntando alla fascia alta in negoziazione.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "prada-group-app-analytics-senior-specialist-milano-2",
    "title": "App Analytics Senior Specialist",
    "company": "Prada Group",
    "location": "Milano (HQ)",
    "remote": null,
    "url": "https://www.businessoffashion.com/careers/job/319832/app-analytics-senior-specialist",
    "source": "Business of Fashion (career page ufficiale Prada Group) — verificato ATTIVO leggendo il testo integrale il 28/08/2026",
    "date_found": "2026-08-28",
    "date_posted": null,
    "key_requirements": [
      "4-6 anni di esperienza in digital analytics, focus mobile app analytics",
      "Piattaforme analytics (Adobe Analytics, Firebase, Amplitude, AppsFlyer, Adjust)",
      "Data visualization (Power BI, Qlik Sense, Tableau, Looker); A/B testing ed experimentation"
    ],
    "technical_match_score": "Fit buono su strumenti di analytics/BI e dashboard, ma il dominio specifico (mobile app analytics, SDK, attribution) è più specialistico/tecnico rispetto al focus BI/forecasting/business del profilo.",
    "economic_fit": "unknown",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO — annuncio distinto e più recente (id 319832, closing date 27 Sep 2026) rispetto al precedente 'App Analytics Lead' (id 309810) già tracciato come scaduto. RAL non dichiarata in questo annuncio specifico, ma un ruolo affine dello stesso team ('App Analytics Lead') dichiarava RAL € 39.000–42.000, sotto la soglia minima di 45k: rischio economico concreto. Grande gruppo lusso italiano, ottimo fit su dimensione/brand. Non genero CV in questa sessione: da verificare la RAL in colloquio prima di investire tempo nella candidatura.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "subito-senior-data-analyst-milano",
    "title": "Senior Data Analyst",
    "company": "Subito",
    "location": "Milano (via Angelo Scarsellini, Affori)",
    "remote": "ibrido, 2 giorni/settimana in ufficio e 3 da remoto (full-remote valutabile per casi specifici in fase di colloquio)",
    "url": "https://it.linkedin.com/jobs/view/senior-data-analyst-at-subito-4452235823",
    "source": "LinkedIn (pagina ufficiale aziendale Subito) — verificato leggendo il testo integrale il 31/08/2026",
    "date_found": "2026-08-31",
    "date_posted": null,
    "key_requirements": [
      "5+ anni di esperienza come Data Analyst in contesti complessi",
      "Estrazione/manipolazione dati su larga scala: SQL, Spark, Pandas/Polars; ottima conoscenza di Python o R",
      "Statistica applicata (regressioni, ANOVA, serie storiche, statistica bayesiana) e data storytelling per stakeholder"
    ],
    "technical_match_score": "Fit molto buono: generazione di insight per il business, dashboard automatizzate e data storytelling per stakeholder sono il core dell'esperienza da Marketing Data Analyst (Mediaset/Publitalia) e Analytics Consultant (Jakala, incl. PySpark/SQL). La statistica avanzata (bayesiana, serie storiche) è meno documentata nel dettaglio nel profilo ma coerente con 'Statistical Modeling' e 'Forecasting Models' già presenti. Seniority richiesta (5+ anni) sostanzialmente in linea con l'esperienza professionale maturata (~5 anni da settembre 2021).",
    "economic_fit": "below_target",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily il 31/08/2026, annuncio pubblicato dalla stessa Subito su LinkedIn). RAL dichiarata 40.000–55.000 € + bonus annuali: il minimo è sotto la soglia non negoziabile di 45k in goals.yaml, ma il massimo supera sia la soglia minima sia il target di 50k — fascia non garantita, da negoziare. Subito è il marketplace leader in Italia (app diffusissima, valutazione utenti 4.8/5): non è un 'grande gruppo' tradizionale come Mediaset, ma è un'azienda digitale di grande scala e visibilità, non una piccola/media impresa o startup (rispetta l'esclusione in search_criteria.yaml). Cultura dichiaratamente data-driven, con framework OKR e forte enfasi tecnica — molto coerente con 'azienda dinamica' e 'cultura del cambiamento' di goals.yaml. Non genero CV in questa sessione: da valutare con l'utente vista l'incertezza sulla fascia economica.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "amplifon-global-customer-intelligence-crm-insights-milano",
    "title": "Global Customer Intelligence & CRM Insights Manager (annuncio dettagliato riporta 'Sr Specialist')",
    "company": "Amplifon",
    "location": "Milano (Sede centrale)",
    "remote": "ibrido, fino a 6 giorni/mese da remoto",
    "url": "https://builtin.com/job/global-customer-intelligence-crm-insights-senior-specialist/9000923",
    "source": "Built In (mirror dettagliato dell'annuncio Amplifon, testo integrale letto il 31/08/2026); posizione confermata anche nell'elenco ufficiale su careers.amplifon.com con titolo 'Global Customer Intelligence & CRM Insights Manager' (Milano), ma la relativa pagina di dettaglio è un'app dinamica non estraibile automaticamente in questo ambiente — verificare titolo/livello esatto sulla pagina ufficiale prima di procedere",
    "date_found": "2026-08-31",
    "date_posted": null,
    "key_requirements": [
      "2-5 anni di esperienza in ruolo analitico, preferibilmente in ambito marketing",
      "SQL, Python o R; Power BI/Tableau un plus",
      "Segmentazione clienti, modelli predittivi di comportamento cliente, analisi campagne CRM"
    ],
    "technical_match_score": "Fit molto buono su strumenti e ambito: raccolta/pulizia dati, analisi comportamento cliente, segmentazione, dashboard e insight per il marketing sono molto vicini all'esperienza Marketing Data Analyst (Mediaset/Publitalia, audience analytics) e Analytics Consultant (Jakala, customer acquisition/retention). Nota: i requisiti di esperienza dell'annuncio dettagliato (2-5 anni) sono sotto la seniority target di 5+ anni, mentre il titolo sull'elenco ufficiale Amplifon è 'Manager' — possibile disallineamento tra titolo e livello richiesto, da chiarire prima di un eventuale colloquio.",
    "economic_fit": "unknown",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO (testo integrale dell'annuncio dettagliato letto via Tavily il 31/08/2026, con nome del manager di riferimento, CCNL Commercio e struttura benefit tipica di un annuncio reale). RAL dichiarata 44.000–62.000 € lordi + bonus di risultato: il minimo è di poco sotto la soglia non negoziabile di 45k in goals.yaml, il massimo è ben oltre il target di 50k — nessuna garanzia sulla fascia effettiva. Amplifon è una multinazionale italiana, leader globale nel settore hearing care (20.300+ dipendenti, 24+ paesi), ottimo fit su dimensione/brand; cultura dichiarata 'drive di una start-up' nonostante le dimensioni, coerente con 'sfide nuove' e crescita reale di goals.yaml. CV generato comunque su richiesta esplicita dell'utente, enfatizzando customer behavior analysis, audience/media analytics, SQL/Python, Power BI e KPI framework realmente presenti nel profilo. Caveat di incertezza economica e possibile disallineamento di seniority (annuncio 2-5 anni vs titolo ufficiale 'Manager') segnalati per la decisione finale dell'utente.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/amplifon-global-customer-intelligence-crm-insights-milano/cv.md"
  },
  {
    "slug": "jnj-senior-data-scientist-ai-scientific-applications-milano",
    "title": "Senior Data Scientist - AI & Scientific Applications",
    "company": "Johnson & Johnson (Innovative Medicine)",
    "location": "Milano (alternativa: Madrid)",
    "remote": null,
    "url": "https://it.talent.com/view?id=633684128854121926",
    "source": "Talent.com (mirror di annuncio Johnson & Johnson, testo integrale letto il 31/08/2026) — ATTENZIONE: la pagina mostra il messaggio \"L'offerta di lavoro non è disponibile nel tuo Paese\" pur visualizzando il testo completo; verificare la posizione direttamente su careers.jnj.com prima di procedere",
    "date_found": "2026-08-31",
    "date_posted": null,
    "key_requirements": [
      "Master o PhD in Data Science, Computer Science, Statistica, Ingegneria o affini",
      "5+ anni di esperienza nella costruzione di soluzioni di data science/ML/AI/analytics",
      "Esperienza hands-on con Large Language Models, Generative AI, prompt design, Retrieval-Augmented Generation, API, database, piattaforme cloud"
    ],
    "technical_match_score": "Fit tecnico parziale: ruolo fortemente orientato a data science/AI engineering hands-on in produzione (LLM, RAG, sviluppo software, MLOps) — il profilo copre Python, SQL, Machine Learning e analytics ma non a livello di ingegnerizzazione/produzione di applicazioni AI generativa. Seniority (5+ anni) in linea con l'esperienza professionale maturata. Settore (scienze della vita/healthcare) distante da media/retail/automotive del profilo, ma il gap è principalmente tecnico (AI engineering vs BI/analytics) più che di dominio.",
    "economic_fit": "ok",
    "mission_fit": "unknown",
    "fit_notes": "RAL per l'Italia dichiarata 48.600–77.395 €: ben sopra sia la soglia minima di 45k sia il target di 50k in goals.yaml. Johnson & Johnson è una multinazionale globale di grandi dimensioni nel settore healthcare/farmaceutico — ottimo fit su dimensione/brand, ma mission/settore (scienze della vita) non ancora confrontato con i valori/cultura in goals.yaml oltre al fit dimensionale. Gap tecnico reale (AI engineering hands-on vs BI/analytics/forecasting del profilo), analogo al caso Sky Italia Manager Data Scientist già in pipeline. Fonte da riverificare su careers.jnj.com per confermare disponibilità effettiva della posizione in Italia. Non genero CV in questa sessione: da valutare con l'utente vista l'incertezza tecnica e la necessità di riverificare la fonte.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "rai-pubblicita-data-analyst-milano",
    "title": "Data Analyst",
    "company": "Rai Pubblicità",
    "location": "Milano",
    "remote": null,
    "url": "https://it.linkedin.com/jobs/view/data-analyst-at-rai-pubblicit%C3%A0-4448098813",
    "source": "LinkedIn (pagina ufficiale aziendale Rai Pubblicità, con informazioni retributive esplicite per obbligo di legge) — verificato il 31/08/2026, pubblicato secondo le fonti tra 15 ore e 3 settimane fa",
    "date_found": "2026-08-31",
    "date_posted": "2026-08 (esatto non determinabile, comunque entro gli ultimi 2 mesi)",
    "key_requirements": [
      "Direzione Business Operations & Innovation, Funzione Data Strategy",
      "Ottimizzazione e valorizzazione dell'ecosistema dati aziendale, metodologie data-driven per innovare i processi",
      "Livello B1 del CCL Rai Pubblicità"
    ],
    "technical_match_score": "Fit di settore ottimo (concessionaria pubblicitaria del servizio pubblico radiotelevisivo — stesso ambito di Publitalia '80/Mediaset già in profile.yaml, audience/advertising data). Fit tecnico da confermare: titolo 'Data Analyst' generico, senza indicazione esplicita di anni di esperienza richiesti nello snippet disponibile — possibile ruolo a seniority inferiore ai 5+ anni target.",
    "economic_fit": "below_target",
    "mission_fit": "ok",
    "fit_notes": "Informazioni retributive dichiarate per obbligo di legge (art. 5 D.Lgs. 96/2026 e Direttiva UE 2023/970): RAL 40.000–48.000 €, livello B1 CCL Rai Pubblicità. Il minimo è sotto la soglia non negoziabile di 45k in goals.yaml, il massimo la supera di poco — fascia non garantita. Rai Pubblicità è la concessionaria pubblicitaria Rai (servizio pubblico radiotelevisivo italiano), settore identico a Publitalia '80/Mediaset del profilo — ottimo fit di mission/settore. Seniority del ruolo non chiara dallo snippet pubblico (LinkedIn richiede login per il testo integrale): da verificare prima di generare il CV. Non genero CV in questa sessione: da valutare con l'utente vista l'incertezza economica e di seniority.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "otb-global-customer-insights-senior-analyst-milano",
    "title": "Global Customer Insights Senior Analyst — CRM",
    "company": "OTB Group",
    "location": "Milano",
    "remote": null,
    "url": "https://it.linkedin.com/jobs/view/global-customer-insights-senior-analyst-at-otb-4448841970",
    "source": "LinkedIn (pagina ufficiale aziendale OTB) — dettagli contrattuali confermati su più mirror (WhatJobs, Trabajo.org, KitLavoro) il 31/08/2026, pubblicato 5 giorni fa",
    "date_found": "2026-08-31",
    "date_posted": "2026-08-26 circa (5 giorni prima del rilevamento)",
    "key_requirements": [
      "2-4 anni di esperienza in CRM, Customer Insights, Data Analytics, idealmente nel lusso/fashion retail premium",
      "Supporto a CRM data governance, segmentazione e analytics"
    ],
    "technical_match_score": "Fit tecnico buono su ambito (CRM analytics, segmentazione clienti, vicino all'esperienza Jakala/Mediaset), ma seniority richiesta (2-4 anni) sotto il target di 5+ anni.",
    "economic_fit": "below_target",
    "mission_fit": "ok",
    "fit_notes": "RAL dichiarata € 35.000–42.000 lordi/anno, confermata su più fonti indipendenti: l'intera fascia è sotto la soglia minima non negoziabile di € 45.000 in goals.yaml, senza alcuna sovrapposizione. Scartato per soglia economica, come da regola 6 di CLAUDE.md (stesso motivo del caso METRO Italia). OTB (Diesel, Maison Margiela, Marni, Jil Sander) è un grande gruppo del lusso italiano — buon fit su dimensione/brand, ma irrilevante vista la RAL interamente fuori soglia.",
    "status": "scartato",
    "discard_reason": "RAL dichiarata € 35.000–42.000 lordi/anno, interamente sotto la soglia minima non negoziabile di € 45.000 in goals.yaml (confermata su più fonti indipendenti).",
    "cv_path": null
  },
  {
    "slug": "bearingpoint-data-scientist-senior-consultant-milano",
    "title": "Data Scientist – Senior Consultant",
    "company": "BearingPoint",
    "location": "Milano (preferita) o Torino",
    "remote": null,
    "url": "https://www.bearingpoint.com/it-it/careers/posizioni-aperte/offer?id=T7944263",
    "source": "Career page ufficiale BearingPoint Italia (contenuto confermato anche su careersitaly.bearingpoint.com e mirror JobLeads) — verificato il 31/08/2026; pagina ufficiale è un'app dinamica, RAL e data di pubblicazione esatta non estraibili automaticamente in questo ambiente",
    "date_found": "2026-08-31",
    "date_posted": null,
    "key_requirements": [
      "4-5 anni di esperienza in Data & Analytics, capacità di progettare e consegnare soluzioni data-driven",
      "Modelli analitici e machine learning (predittivo ed esplorativo), forte programmazione Python",
      "Ambienti cloud (AWS/Azure/GCP, Databricks), esposizione a Generative AI/LLM e prompt engineering"
    ],
    "technical_match_score": "Fit molto buono su seniority (4-5 anni, in linea con l'esperienza reale di ~5 anni) e su Python/ML/cloud del profilo. Ambito più orientato a data science/ML applicato in contesti multi-industry di consulenza che a BI/reporting puro, ma con enfasi su 'business impact' e presentazione risultati end-to-end coerente con l'esperienza Jakala (Analytics Consultant, client-facing).",
    "economic_fit": "unknown",
    "mission_fit": "ok",
    "fit_notes": "BearingPoint è una società di consulenza management/technology internazionale di buon livello (non top-3 strategy ma paragonabile per tipologia a EY-Parthenon/Deloitte già in pipeline) — coerente col criterio 'consulenza di alto livello'. RAL non dichiarata nell'annuncio (pagina ufficiale dinamica, non estraibile automaticamente): da verificare in colloquio. Data di pubblicazione esatta non determinabile, ma annuncio trovato attivo e coerente su più fonti il 31/08/2026. Non genero CV in questa sessione: da valutare con l'utente vista l'incertezza economica.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "engie-italia-forecasting-data-scientist-milano",
    "title": "Data Scientist Forecasting",
    "company": "ENGIE Italia S.p.A.",
    "location": "Milano",
    "remote": null,
    "url": "https://jobs.engie.com/job/Data-Scientist-Forecasting/65707-en_US/",
    "source": "Career page ufficiale ENGIE (link fornito dall'utente) — verificato ATTIVO leggendo il testo integrale il 31/08/2026 (Posting Start Date: 8/4/26, pulsante Apply funzionante)",
    "date_found": "2026-08-31",
    "date_posted": "2026-08-04",
    "key_requirements": [
      "2+ anni di esperienza in forecasting, data science o analisi quantitativa, preferibilmente nel settore energy",
      "Python e R, time series forecasting, piattaforme dati moderne (Databricks, Spark), ambienti cloud analytics",
      "Master o PhD in matematica applicata, ingegneria, data science, fisica o economia"
    ],
    "technical_match_score": "Fit tecnico molto buono: il ruolo è specificamente focalizzato sul forecasting (modelli, processi, miglioramento continuo) e sulla traduzione di dati complessi in insight azionabili per stakeholder di business — corrisponde quasi puntualmente a 'Designed forecasting models to support business planning...' e 'Built market and revenue estimation models...' già in profile.yaml (Mediaset/Publitalia). Python presente nel profilo, R non documentato (solo Python/SQL/PySpark). Requisito di esperienza (2+ anni) sotto il target di 5+ anni indicato in search_criteria.yaml, ma il range salariale 'a seconda di esperienza e seniority' suggerisce un ruolo scalabile anche per profili più senior.",
    "economic_fit": "below_target",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto direttamente dalla career page ufficiale ENGIE, candidatura aperta). RAL dichiarata € 39.000–53.500 lordi/anno 'a seconda di esperienza e livello di seniority': il minimo è sotto la soglia non negoziabile di 45k in goals.yaml, il massimo supera sia la soglia minima sia il target di 50k — fascia scalabile ma non garantita. ENGIE è una multinazionale energetica globale di grandi dimensioni (30+ paesi) con missione esplicita di transizione energetica/decarbonizzazione e certificazioni su diversità e inclusione (ISO 30415, UNI PDR 125) — ottimo fit su dimensione/brand e forte coerenza con il valore 'innovazione responsabile, attenzione all'impatto su società' di goals.yaml. CV generato su richiesta esplicita dell'utente nonostante l'incertezza sulla fascia economica, enfatizzando in particolare le esperienze di forecasting (Mediaset) realmente presenti nel profilo.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/engie-italia-forecasting-data-scientist-milano/cv.md"
  },
  {
    "slug": "snam-corporate-strategy-business-intelligence-analyst-milano",
    "title": "Corporate Strategy & Business Intelligence Analyst",
    "company": "Snam S.p.A.",
    "location": "Milano",
    "remote": "ibrido (modello di lavoro flessibile con possibilità di remoto)",
    "url": "https://it.linkedin.com/jobs/view/corporate-strategy-business-intelligence-analyst-at-snam-s-p-a-4440587557",
    "source": "LinkedIn (pagina ufficiale aziendale Snam) — verificato leggendo il testo integrale il 01/09/2026, pubblicato 1 mese fa",
    "date_found": "2026-09-01",
    "date_posted": "2026-08 circa (1 mese prima del rilevamento)",
    "key_requirements": [
      "Laurea magistrale in Economia, Ingegneria, STEM o discipline affini, con 1-3 anni di esperienza professionale rilevante",
      "Monitoraggio dell'evoluzione del settore energetico (mercati gas/elettricità, decarbonizzazione, nuove tecnologie), trasformazione di informazioni complesse in insight strategici",
      "Livello di anzianità: esperienza minima"
    ],
    "technical_match_score": "Fit tecnico buono su ambito (analisi di mercato, trasformazione di dati complessi in insight strategici per il management, preparazione di materiali executive) — coerente con l'esperienza di supporto a decisioni strategiche e recommendation per senior stakeholder già in profile.yaml (Mediaset). Seniority richiesta (1-3 anni, 'esperienza minima') nettamente sotto il target di 5+ anni in search_criteria.yaml: ruolo probabilmente troppo junior rispetto al profilo.",
    "economic_fit": "below_target",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily il 01/09/2026, annuncio con informativa retributiva esplicita per obbligo di legge). RAL minima dichiarata € 43.600 lordi/anno (CCNL Energia e Petrolio, possibile contratto di apprendistato), sotto la soglia non negoziabile di 45k in goals.yaml. Snam è una delle principali multinazionali italiane quotate nel settore infrastrutture energetiche (trasporto/stoccaggio/rigassificazione gas, leader europeo) — ottimo fit su dimensione/brand, con missione di decarbonizzazione coerente con 'innovazione responsabile' di goals.yaml. Ruolo probabilmente troppo junior (esperienza minima 1-3 anni) rispetto ai 5+ anni target, oltre alla RAL sotto soglia. Non genero CV in questa sessione: da valutare con l'utente vista la doppia incertezza (seniority ed economica).",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  },
  {
    "slug": "nielseniq-senior-analytics-consultant-rgm-milano",
    "title": "Senior Analytics Consultant - Revenue Growth Management (RGM)",
    "company": "NielsenIQ",
    "location": "Milano",
    "remote": "ibrido (almeno 1 giorno/settimana in ufficio)",
    "url": "https://it.linkedin.com/jobs/view/senior-analytics-consultant-revenue-growth-management-rgm-at-nielseniq-4459744704",
    "source": "LinkedIn (pagina ufficiale aziendale NielsenIQ) — verificato leggendo il testo integrale il 01/09/2026",
    "date_found": "2026-09-01",
    "date_posted": null,
    "key_requirements": [
      "3+ anni di esperienza in RGM (Revenue Growth Management) o Category Management nel settore FMCG",
      "Gestione di progetti RGM end-to-end per clienti FMCG, pricing e promozioni",
      "Ottimo Excel e PowerPoint; Power BI un plus"
    ],
    "technical_match_score": "Fit moderato: ruolo di consulenza analitica su pricing/revenue per clienti FMCG, traduzione di dati in raccomandazioni azionabili — trasferibile dall'esperienza Analytics Consultant (Jakala) e dai modelli di stima di mercato/revenue (Mediaset), ma il dominio specifico FMCG/RGM non è documentato nel profilo. Seniority (3+ anni) leggermente sotto il target di 5+ anni.",
    "economic_fit": "below_target",
    "mission_fit": "unknown",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily il 01/09/2026). RAL dichiarata € 35.000-45.000 lordi/anno: l'intera fascia è pari o sotto la soglia minima non negoziabile di 45k in goals.yaml, senza margine sopra soglia. Scartato per soglia economica, come da regola 6 di CLAUDE.md (stesso motivo dei casi METRO Italia e OTB Group). NielsenIQ è una multinazionale globale leader in consumer intelligence — buon fit su dimensione/brand, ma irrilevante vista la RAL non sopra soglia.",
    "status": "scartato",
    "discard_reason": "RAL dichiarata € 35.000-45.000 lordi/anno: l'intera fascia è pari o sotto la soglia minima non negoziabile di € 45.000 in goals.yaml, senza margine sopra soglia.",
    "cv_path": null
  },
  {
    "slug": "bulgari-data-scientist-rome",
    "title": "Data Scientist",
    "company": "Bulgari (LVMH)",
    "location": "Roma",
    "remote": "in presenza",
    "url": "https://www.lvmh.com/en/join-us/our-job-offers/BULG08927",
    "source": "Career page ufficiale LVMH/Bulgari (rif. BULG08927) — verificato ATTIVO leggendo il testo integrale il 01/09/2026, pubblicato 04-Aug-2026",
    "date_found": "2026-09-01",
    "date_posted": "2026-08-04",
    "key_requirements": [
      "Almeno 5 anni di esperienza in Data Science, Machine Learning, predictive analytics o applied AI",
      "Python avanzato (Pandas, NumPy, Scikit-learn, TensorFlow/PyTorch), SQL, cloud analytics",
      "Esperienza di produzione/industrializzazione di soluzioni AI/ML: MLOps, CI/CD, model deployment/monitoring; familiarità con GenAI/LLM/RAG/agentic AI un plus"
    ],
    "technical_match_score": "Fit tecnico parziale: il ruolo è fortemente orientato all'industrializzazione e produzione di soluzioni AI/ML (MLOps, CI/CD, model deployment, GenAI/agentic AI) — il profilo copre Python, SQL, Machine Learning e statistical modeling ma non a livello di ML engineering/produzione. Seniority (5+ anni) pienamente in linea con l'esperienza professionale maturata. Gap tecnico analogo ai casi Sky Italia Manager Data Scientist e Johnson & Johnson già in pipeline (ML engineering hands-on vs BI/analytics/forecasting del profilo).",
    "economic_fit": "ok",
    "mission_fit": "ok",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto direttamente dalla career page ufficiale LVMH, candidatura aperta). RAL dichiarata € 50.000 lordi/anno fissi per i nuovi assunti in Italia (CCNL Terziario, Distribuzione e Servizi) — esattamente in linea col target di goals.yaml, sopra la soglia minima di 45k. Bulgari fa parte di LVMH, il più grande gruppo del lusso al mondo — eccellente fit su dimensione/brand; impegno dichiarato su responsabilità sociale/ambientale (Fondazione Bvlgari) coerente con 'innovazione responsabile' di goals.yaml. Sede Roma (non Milano/hinterland preferito, ma Italia accettabile per grandi aziende) e modalità in presenza (non ibrido). CV generato in questa sessione: Fase 4 pienamente superata (economic_fit e mission_fit entrambi ok), enfatizzando Python/ML/statistical modeling/forecasting realmente presenti nel profilo; gap di ML engineering/produzione segnalato per la decisione finale dell'utente.",
    "status": "cv pronto",
    "discard_reason": null,
    "cv_path": "cv/generated/bulgari-data-scientist-rome/cv.md"
  },
  {
    "slug": "loro-piana-crm-manager-new-york",
    "title": "CRM Manager",
    "company": "Loro Piana (LVMH)",
    "location": "New York, USA (regione Americas)",
    "remote": null,
    "url": "https://www.loropiana.com/career/details.php?jobId=1089929&jobTitle=Loro+Piana+-+CRM+Manager",
    "source": "Career page ufficiale Loro Piana (LVMH) — verificato leggendo il testo integrale il 01/09/2026",
    "date_found": "2026-09-01",
    "date_posted": null,
    "key_requirements": [
      "5-7 anni di esperienza in CRM, customer management, client development o data analytics, preferibilmente in lusso/fashion/retail",
      "Esperienza con piattaforme CRM e strumenti di Business Intelligence reporting",
      "Traduzione di dati cliente in raccomandazioni di business azionabili, gestione KPI CRM e reportistica"
    ],
    "technical_match_score": "Fit tecnico molto buono: analisi comportamento cliente, KPI CRM, reportistica per stakeholder senior — molto vicino all'esperienza Jakala (customer acquisition/retention) e Mediaset (audience analytics, dashboard KPI). Seniority (5-7 anni) coerente col target. Ambito CRM/marketing (non puro BI/forecasting) leggermente diverso ma trasferibile.",
    "economic_fit": "unknown",
    "mission_fit": "unknown",
    "fit_notes": "VERIFICATO ATTIVO (testo integrale letto via Tavily il 01/09/2026, candidatura aperta). Loro Piana fa parte di LVMH (come Bulgari già in pipeline) — eccellente fit su dimensione/brand. ATTENZIONE: sede a New York, USA, non Milano/Italia — comporterebbe un trasferimento permanente, non un assignment breve. goals.yaml indica apertura sia a 'brevi esperienze all'estero' sia a 'posizioni intere all'estero', quindi non è escluso dai criteri, ma è una scelta di vita significativa da valutare con l'utente. RAL non dichiarata nell'annuncio (prassi USA, nessun obbligo di trasparenza salariale mostrato) — nessuna verifica economica possibile. Mission/cultura aziendale specifica del team Americas non approfondita. Non genero CV in questa sessione: da valutare con l'utente sia per l'incertezza economica sia per l'implicazione di trasferimento permanente negli USA.",
    "status": "da valutare",
    "discard_reason": null,
    "cv_path": null
  }
];
